Multi-stage Dockerfile
cisco-ie/pipeline-gnmi pull request #54
Opened 2019-05-31 19:06 UTC by remingtonc

Should we use alpine or stretch as base for image?

2019-06-01 02:23 UTC, nleiva commented
To build the binary, `golang:1.12-stretch` as you selected.

For the final image with this (Pipeline) binary I'd say we want `alpine`. You typically want to reduce the attack surface and use something like [distroless](https://github.com/GoogleContainerTools/distroless#examples-with-docker), however in this case we need a shell and a package manager for troubleshooting purposes I think (might be off here though).

The new Dockerfile looks much better now. Something else we can add, that I haven't tested yet but looks promising, is `ENV GOPROXY=proxy.golang.org` -> [Go Module Mirror](https://proxy.golang.org/)

2019-06-01 03:18 UTC, nleiva requested changes
The default is Alpine 3.7 or the link is misleading?

```bash
 ---> Running in ed54d28ec3ee
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/3) Installing libcrypto1.0 (1.0.2r-r0)
...
```

2019-06-04 15:57 UTC, remingtonc commented
@nleiva It's most likely that `alpine:latest` is cached and it's 3.7. `docker pull alpine`

2019-06-07 18:57 UTC, nleiva approved these changes

2019-06-18 21:33 UTC, merged