Recommend Telegraf in README
cisco-ie/pipeline-gnmi pull request #59
Opened 2020-04-21 04:07 UTC by remingtonc

Recommend Telegraf in the README, seem reasonable?

2020-07-06 18:48 UTC, remingtonc commented
ping

2020-07-14 16:57 UTC, skkumaravel requested changes

2020-07-14 16:57 UTC, skkumaravel commented on README.md
> +**NOTE**: Please evaluate usage of the following [Telegraf](https://github.com/influxdata/telegraf) plugins for your use case: [cisco_telemetry_mdt](https://github.com/influxdata/telegraf/tree/master
I would reword, have the reason upfront. Something like, "For a more recently developed gnmi collector and allow all the benefits of the Telegraf ecosystem, please evaluate usage of the following ..."

2020-07-14 16:57 UTC, skkumaravel commented on README.md
> +`pipeline-gnmi` is a Model-Driven Telemetry (MDT) collector based on the open-source tool [`pipeline`](https://github.com/cisco/bigmuddy-network-telemetry-pipeline) which has improved maintainability
improved maintainability and compatibility than what? awkward sentence.

2020-07-15 18:32 UTC, skkumaravel approved these changes
LGTM now

2020-07-15 18:43 UTC, merged